spring.application.name=suggestionServices

server.port = 8085


# Gemini Vertex AI setup

#api key
gemini.api.key = AIzaSyABNAxm1rlEYOFaca6KeUkMgTzVXzUNRjc

#model name
gemini.base.url=https://generativelanguage.googleapis.com
gemini.model=gemini-2.5-flash






